language: python
python:
  - "3.6"
  matrix:
    include:
      - python: 3.7
        dist: xenial
# command to install dependencies
before_install:
  - pip install poetry
install:
  - poetry install -v
  - pip install tox-travis
# command to run tests
script:
  - tox
