language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
before_install:
  - pip install poetry
install:
  - poetry install -v
  - pip install tox-travis
# command to run tests
script:
  - tox
